name: sportwin_predictor
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  # bloc
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  equatable: ^2.0.3
  # web
  dio: ^4.0.6
  # local
  shared_preferences: ^2.0.15
  # formatting
  intl: ^0.17.0



  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  google_fonts: ^3.0.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icon/icon_final.png"
  ios: true
  android: true

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/_.png
    - assets/images/dollar.png
    - assets/images/heart.png
    - assets/images/i.png
    - assets/images/love_disable.png
    - assets/images/play.png
    - assets/images/star_disabled.png
    - assets/images/star.png
    - assets/images/mask_group.png
